### ISSUE TITLE
TIPS for implement maxmin-cnn in caffe.

### ISSUE THREAD

**Issue by silverlining21** [karandesai-96/maxmin-cnn#4]
@karandesai-96 

Since the latest caffe have already implemented `Scale layer ` and `Concat layer `, we  don't need to re-implement the `maxmin-conv layer `. we can simply combine the two layer above. 

here is the simple example for network configure:

```````

................form conv layer..............
layer {
    bottom: "conv1"
    top: "sacle_conv1"
    name: "sacle_conv1"
    type: "Scale"
	
	scale_param {
		filler {
		  value: -1    }
		bias_term: true
		bias_filler {
		  value: 0
		}
    }
}

layer {
	name: "concat_conv1"
	bottom: "conv1"
	bottom: "sacle_conv1"
	top: "concat_conv1"
	type: "Concat"
	
	concat_param{
		axis: 1
	}

}


........following by relu............
```````
scale layer -> out = in*\alpha + \beta(here alpha=-1, beta=0)
concat layer -> if axis=1 concat at channels; axis=0 concat at num.

hope that helps.

**Comment by karandesai-96** [comment]
@silverlining21 Thanks, I really appreciate that. :smile:

> we don't need to re-implement the maxmin-conv layer. 

Okay just for the information, Keras has Concat , Merge and Lambda layers so similar idea could be done in Keras but I chose it implement it in a class to treat the whole layer as a black box, you can see in the notebook, the network visualisation still looks like sequential network without any branches. 

Although not necessary to do the same in caffe, your idea looks perfectly fine !

Would you like to contribute to the repo ? You can open your PR and I would be happy to credit your idea, and merge it. It can be a simple plug and play piece of code which anyone can copy paste in this in their code, maybe this same snippet with a helpful inline comment or an accompanying _README_ for its usage, all in one directory ?

**Comment by silverlining21** [comment]
> Would you like to contribute to the repo ? You can open your PR and I would be happy to credit your idea, and merge it. It can be a simple plug and play piece of code which anyone can copy paste in this in their code, maybe this same snippet with a helpful inline comment or an accompanying README for its usage, all in one directory ?


OK, I will give it a try.
